language: python
dist: jammy
python:
  - "3.8"
services:
  - docker

cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache

install:
  - cd $TRAVIS_BUILD_DIR
  - ./bin/install_ci_dependencies.sh
jobs:
  include:
    - stage: build-and-deploy-plugin
      if: commit_message =~ /^update-plugin-.+$/
      script: 
      - cd $TRAVIS_BUILD_DIR/ecr
      - mvn install -U -DskipTests=true -Dmaven.javadoc.skip=true -T 4 -B -V
      - docker build -t cqf-ruler:$TRAVIS_COMMIT .
      - cd ../
      - ./bin/deploy_plugin.sh
    - stage: test
      script: 
      - cd $TRAVIS_BUILD_DIR/vsm-app
      - npm ci && npm run test-ci
      install: skip
    - stage: deploy
      if: branch IN (main)
      script:
        - cd $TRAVIS_BUILD_DIR/vsm-app
        # TODO: Disabled for now as it stopped working with permission errors
        # - git config user.name 'Travis CI User'
        # - git remote set-url origin https://$GITHUB_TOKEN@github.com/DBCG/aphl-vsm.git
        # - npm version patch
        # - git add .
        # - git commit -m "update version number [ci skip]"
        # - git push origin HEAD:$TRAVIS_BRANCH || travis_terminate 1
        - docker build -t vsm-app:$TRAVIS_COMMIT .
        - cd ../
        - ./bin/deploy.sh
