version: '3.8'

volumes:
  cqf_db_data:
    driver: local
  postgres_data:
    driver: local
services:

  redis:
    image: redis:latest
    ports:
    - 6379:6379
  cqf-ruler-vsm:
    image: alphora/cqf-ruler:cqf-ruler-vsm
    environment:
      - spring.datasource.url=jdbc:postgresql://cqf-db:5432/cqfruler
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.datasource.username=myuser
      - spring.datasource.password=secret
      - spring.jpa.properties.hibernate.dialect=ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      - hapi.fhir.server_address=http://localhost:8082/fhir
      - hapi.fhir.cql.cql_logging_enabled=true
      - hapi.fhir.fhir_version=R4
      - hapi.fhir.allow_multiple_delete=true
      # - hapi.fhir.security.enabled=true
      # - hapi.fhir.security.basic_auth.enabled=true
      # - hapi.fhir.security.basic_auth.username=admin
      # - hapi.fhir.security.basic_auth.password=password
    ports:
      - 8082:8080
    depends_on:
      - cqf-db
  cqf-db:
    image: postgres:9.4.26-alpine
    volumes:
      - cqf_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cqfruler
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
  postgres:
    image: postgres:9.4.26-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    command: 'start'
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
    depends_on:
      - postgres
  # vsm-app:
  #   build:
  #     context: ./vsm-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - ./vsm-app/.env.local