version: '3.8'

volumes:
  cqf_db_data:
    driver: local
  postgres_data:
    driver: local
services:

  redis:
    image: redis:latest
    ports:
    - 6379:6379
  cqf-ruler-vsm:
    image: alphora/cqf-ruler:vsm_draft_operation
    environment:
      - spring.datasource.url=jdbc:postgresql://cqf-db:5432/cqfruler
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.datasource.username=myuser
      - spring.datasource.password=secret
      - spring.jpa.properties.hibernate.dialect=ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      - hapi.fhir.server_address=http://localhost:8082/fhir
      - hapi.fhir.cql.cql_logging_enabled=true
      - hapi.fhir.fhir_version=R4
    ports:
      - 8082:8080
    depends_on:
      - cqf-db
  cqf-db:
    image: postgres
    volumes:
      - cqf_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cqfruler
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8080:8080
      depends_on:
        - postgres