apiVersion: v1
kind: Service
metadata:
  name: cqf-ruler-vsm
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: cqf-ruler-vsm
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cqf-ruler-vsm
  labels:
    app: cqf-ruler-vsm
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cqf-ruler-vsm
  template:
    metadata:
      labels:
        app: cqf-ruler-vsm
    spec:
      containers:
        - image: {{ .Values.aws.account_id }}.dkr.ecr.us-east-1.amazonaws.com/cqf-ruler:{{ .Values.tag }}
          imagePullPolicy: Always
          name: cqf-ruler-vsm
          env:
            - name: hapi.fhir.server_address
              value: http://localhost:8080/fhir
            - name: hapi.fhir.allow_multiple_delete
              value: "true"
            - name: hapi.fhir.fhir_version
              value: R4
            - name: hapi.fhir.cql.cql_logging_enabled
              value: "true"
            - name: spring.datasource.url
              value: {{ .Values.cqf_ruler.db_url }}
            - name: spring.datasource.driverClassName
              value: org.postgresql.Driver
            - name: spring.datasource.username
              value: dbadmin
            - name: hapi.fhir.security.enabled
              value: "true"
            - name: hapi.fhir.reuse_cached_search_results_millis
              value: "-1"
            - name: hapi.fhir.security.basic_auth.enabled
              value: "true"
            - name: hapi.fhir.security.basic_auth.username
              value: admin
            - name: hapi.fhir.security.basic_auth.password
              valueFrom:  
                secretKeyRef:
                  name: vsm-app-secrets
                  key: cqf-ruler-basic-auth-password
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: prod-db-passwords
                  key: vsm-db-password
            - name: spring.jpa.properties.hibernate.dialect
              value: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
          ports:
            - containerPort: 8080
              protocol: TCP
