apiVersion: v1
kind: Service
metadata:
  name: hapi-fhir-jpa-server-starter
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: hapi-fhir-jpa-server-starter
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hapi-fhir-jpa-server-starter
  labels:
    app: hapi-fhir-jpa-server-starter
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hapi-fhir-jpa-server-starter
  template:
    metadata:
      labels:
        app: hapi-fhir-jpa-server-starter
    spec:
      containers:
        - image: hapiproject/hapi:v8.4.0-3
          imagePullPolicy: Always
          name: hapi-fhir-jpa-server-starter
          resources:
            requests:
              memory: "6.5Gi"
              cpu: "1000m"
            limits:
              memory: "7Gi"
              cpu: "1200m"
          env:
            - name: hapi.fhir.server_address
              value: {{.Values.protocol}}://{{ .Values.hapi_fhir_jpa_server_starter.app_url}}/fhir
            - name: hapi.fhir.allow_multiple_delete
              value: "true"
            - name: hapi.fhir.fhir_version
              value: R4
            - name: hapi.fhir.cql.cql_logging_enabled
              value: "true"
            - name: spring.datasource.hikari.maximum-pool-size
              value: "30"
            - name: redis.host
              value: {{ .Values.vsm_app.redis_host_url}}
            - name: redis.port
              value: "6379"
            - name: redis.database
              value: "4"
            - name: _JAVA_OPTIONS
              value: '-Xmx6500m'
            - name: spring.datasource.url
              value: {{ .Values.hapi_fhir_jpa_server_starter.db_url }}
            - name: spring.datasource.driverClassName
              value: org.postgresql.Driver
            - name: spring.datasource.username
              value: smile_cr
            - name: hapi.fhir.security.enabled
              value: "true"
            - name: hapi.fhir.logger.format
              value: >
                Path[$${servletPath}] Source[$${requestHeader.x-forwarded-for}]
                Trace[$${requestHeader.x-b3-traceid}]
                Operation[$${operationType} $${operationName} $${idOrResourceName}]
                UA[$${requestHeader.user-agent}] Params[$${requestParameters}]
                ResponseEncoding[$${responseEncodingNoDefault}]
            - name: hapi.fhir.reuse_cached_search_results_millis
              value: "-1"
            - name: hapi.fhir.security.basic_auth.enabled
              value: "false"
            - name: hapi.fhir.security.basic_auth.username
              value: admin
            - name: hapi.fhir.casereporting.enabled
              value: "true"
            - name: hapi.fhir.rulercr.enabled
              value: "true"
            - name: hapi.fhir.rulercr.vsac-username
              value: apikey
            - name: hapi.fhir.rulercr.vsac-api-key
              valueFrom:
                secretKeyRef:
                  name: vsm-app-secrets
                  key: vsac-api-key
            - name: hapi.fhir.security.basic_auth.password
              valueFrom:  
                secretKeyRef:
                  name: vsm-app-secrets
                  key: cqf-ruler-basic-auth-password
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: prod-db-passwords
                  key: vsm-db-password
            - name: spring.jpa.properties.hibernate.dialect
              value: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
            - name: hapi.fhir.cr.enabled
              value: "true"
            - name: hapi.fhir.cds.hooks.enabled
              value: "true"
            - name: hapi.fhir.cdshooks.clientIdHeaderName
              value: "client_id"
            - name: spring.main.allow-circular-references
              value: "true"
            - name: spring.main.allow-bean-definition-overriding
              value: "true"
          ports:
            - containerPort: 8080
              protocol: TCP
      nodeSelector:
        kubernetes.io/memory-intensive: "true"
      tolerations:
      - key: "memory-intensive"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/memory-intensive"
                operator: In
                values:
                - "true"
