apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: vsm
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: vsm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - image: quay.io/keycloak/keycloak:legacy
          imagePullPolicy: IfNotPresent
          name: keycloak
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: {{ .Values.keycloak_db_url }}
            - name: KC_DB_SCHEMA
              value: public
            - name: KC_DB_NAME
              value: keycloak
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: false
            - name: KC_HTTP_ENABLED
              value: true
            - name: KC_HOSTNAME
              value: localhost
            - name: KC_HOSTNAME_STRICT
              value: false
            - name: KC_DB_USERNAME
              value: dbadmin
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vsm-app-secrets
                  key: vsm-keycloak-db-password
          ports:
            - containerPort: 8080
              protocol: TCP
