{{ if ne .Values.namespace "vsm-qa" }}
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - image: {{ .Values.keycloak.image }}
          imagePullPolicy: IfNotPresent
          command: ["/opt/keycloak/bin/kc.sh", "start"]
          name: keycloak
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: {{ .Values.keycloak.db_url }}
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: {{ .Values.keycloak.app_url }}
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vsm-app-secrets
                  key: keycloak-admin-password
            - name: KC_DB_USERNAME
              value: smile_cr
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-db-passwords
                  key: keycloak_db_password
          ports:
            - containerPort: 8080
              protocol: TCP
{{ end }}