apiVersion: v1
kind: Service
metadata:
  name: vsm-app
  namespace: {{ .Values.namespace }}
  labels:
    tag: {{ .Values.tag }}
spec:
  type: LoadBalancer
  selector:
    app: vsm-app
  ports:
  - name: http 
    port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsm-app
  namespace: {{ .Values.namespace }}
  labels:
    app: vsm-app
    tag: {{ .Values.tag }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsm-app
  template:
    metadata:
      labels:
        app: vsm-app
    spec:
      containers:
      - image: {{ .Values.aws.account_id }}.dkr.ecr.us-east-1.amazonaws.com/vsm-app:{{ .Values.tag }}
        name: vsm-app
        imagePullPolicy: Always
        env:
        - name: PROTOCOL
          value: {{.Values.protocol}}
        - name: FHIR_CDR_URL
          value: http://cqf-ruler-vsm/fhir
        - name: ENABLE_CACHE
          value: "false"
        - name: EXTERNAL_FHIR_CDR_URL
          value: {{.Values.protocol}}://{{ .Values.vsm_app.app_url }}/fhir
        - name: NEXT_PUBLIC_VSAC_BASE_URL
          value: https://cts.nlm.nih.gov/fhir
        - name: NEXT_PUBLIC_ONTOSERVER_R4_BASE_URL
          value: https://r4.ontoserver.csiro.au/fhir
        - name: REDIS_HOST
          value: {{ .Values.vsm_app.redis_host_url}}
        - name: REDIS_DB
          value: "{{ .Values.vsm_app.redis_db }}"
        - name: VSAC_USERNAME
          value: apikey
        - name: KEY
          valueFrom:  
            secretKeyRef:
              name: encryption-key
              key: encryption-key
        - name: NEXTAUTH_URL
          value: {{.Values.protocol}}://{{ .Values.vsm_app.app_url }}
        - name: KEYCLOAK_ID
          value: aphl_app
        - name: CONDITIONS_CANONICAL
          value: http://ersd.aimsplatform.org/fhir/ValueSet/rckms-condition-codes
        - name: FHIR_CDR_BASIC_AUTH_USERNAME
          value: admin
        - name: FHIR_CDR_BASIC_AUTH_PASSWORD
          valueFrom:  
            secretKeyRef:
              name: vsm-app-secrets
              key: cqf-ruler-basic-auth-password
        - name: KEYCLOAK_SECRET
          valueFrom:  
            secretKeyRef:
              name: vsm-app-secrets
              key: keycloak-secret
        - name: KEYCLOAK_ISSUER
          value: {{.Values.protocol}}://{{ .Values.keycloak.app_url }}/realms/aphl
        - name: KEYCLOAK_REDIRECT_URI
          value: {{.Values.protocol}}://{{ .Values.vsm_app.app_url }}/api/auth/callback/keycloak
        - name: VSAC_API_KEY
          valueFrom:
            secretKeyRef:
              name: vsm-app-secrets
              key: vsac-api-key
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: vsm-app-secrets
              key: nextauth-secret
        ports:
        - containerPort: 3000
          protocol: TCP