tag: ""
namespace: "vsm"
cqf_ruler:
  db_url: "jdbc:postgresql://vsm-cqf-ruler-db.cdarvwauzkgh.us-east-1.rds.amazonaws.com:5432/vsmcqfruler"
vsm_app:
  app_url: "a7cda59b6554642618d1100dc6e3d8ce-1463857425.us-east-1.elb.amazonaws.com"
  redis_host_url: "redis-cache.5hhpo0.ng.0001.use1.cache.amazonaws.com"
  redis_db: "1"
keycloak:
  app_url: "a277b15a1bef34b5da8a6af142026e21-1645222855.us-east-1.elb.amazonaws.com"
  db_url: "jdbc:postgresql://vsm-keycloak-db.cdarvwauzkgh.us-east-1.rds.amazonaws.com:5432/keycloak"
  image: "quay.io/keycloak/keycloak:21.1.2"
protocol: "http"
aws:
  account_id: "912275679263"
