FROM node:18-alpine

# Disable telemetry
ENV NEXT_TELEMETRY_DISABLED=1

RUN apk update
RUN apk add --no-cache curl
RUN apk add --no-cache bash

RUN mkdir -p /opt/app

WORKDIR /opt/app
COPY ./package.json /opt/app
COPY ./package-lock.json /opt/app

RUN npm ci

COPY ./ /opt/app
RUN npm run build

CMD ["npm", "start"]